#!/usr/bin/env php
<?php

use Monoelf\Framework\console\ConsoleKernelInterface;
use Monoelf\Framework\container\DIContainer;

error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);

const PROJECT_ROOT = __DIR__;

require_once PROJECT_ROOT . '/vendor/autoload.php';

$container = DIContainer::create(require_once PROJECT_ROOT . '/config/di-console.php');

$kernel = $container->get(ConsoleKernelInterface::class);

$kernel->registerCommandNamespaces([
    '@modules/cost_calculator/commands',
]);

$status = $kernel->handle();

$kernel->terminate($status);
