<?php

declare(strict_types=1);

return [
        ['id' => 1, 'raw_type_id' => 2, 'month_id' => 1, 'tonnage_id' => 2, 'price' => 145],
        ['id' => 2, 'raw_type_id' => 2, 'month_id' => 1, 'tonnage_id' => 3, 'price' => 136],
        ['id' => 3, 'raw_type_id' => 2, 'month_id' => 1, 'tonnage_id' => 4, 'price' => 138],
        ['id' => 4, 'raw_type_id' => 2, 'month_id' => 2, 'tonnage_id' => 2, 'price' => 118],
        ['id' => 5, 'raw_type_id' => 2, 'month_id' => 2, 'tonnage_id' => 3, 'price' => 137],
        ['id' => 6, 'raw_type_id' => 2, 'month_id' => 2, 'tonnage_id' => 4, 'price' => 142],
        ['id' => 7, 'raw_type_id' => 2, 'month_id' => 3, 'tonnage_id' => 2, 'price' => 119],
        ['id' => 8, 'raw_type_id' => 2, 'month_id' => 3, 'tonnage_id' => 3, 'price' => 141],
        ['id' => 9, 'raw_type_id' => 2, 'month_id' => 3, 'tonnage_id' => 4, 'price' => 117],
        ['id' => 10, 'raw_type_id' => 2, 'month_id' => 4, 'tonnage_id' => 2, 'price' => 121],
        ['id' => 11, 'raw_type_id' => 2, 'month_id' => 4, 'tonnage_id' => 3, 'price' => 137],
        ['id' => 12, 'raw_type_id' => 2, 'month_id' => 4, 'tonnage_id' => 4, 'price' => 124],
        ['id' => 13, 'raw_type_id' => 2, 'month_id' => 5, 'tonnage_id' => 2, 'price' => 122],
        ['id' => 14, 'raw_type_id' => 2, 'month_id' => 5, 'tonnage_id' => 3, 'price' => 131],
        ['id' => 15, 'raw_type_id' => 2, 'month_id' => 5, 'tonnage_id' => 4, 'price' => 147],
        ['id' => 16, 'raw_type_id' => 2, 'month_id' => 6, 'tonnage_id' => 2, 'price' => 147],
        ['id' => 17, 'raw_type_id' => 2, 'month_id' => 6, 'tonnage_id' => 3, 'price' => 143],
        ['id' => 18, 'raw_type_id' => 2, 'month_id' => 6, 'tonnage_id' => 4, 'price' => 112],

        ['id' => 19, 'raw_type_id' => 3, 'month_id' => 1, 'tonnage_id' => 1, 'price' => 121],
        ['id' => 20, 'raw_type_id' => 3, 'month_id' => 1, 'tonnage_id' => 2, 'price' => 118],
        ['id' => 21, 'raw_type_id' => 3, 'month_id' => 1, 'tonnage_id' => 3, 'price' => 137],
        ['id' => 22, 'raw_type_id' => 3, 'month_id' => 1, 'tonnage_id' => 4, 'price' => 142],
        ['id' => 23, 'raw_type_id' => 3, 'month_id' => 2, 'tonnage_id' => 1, 'price' => 137],
        ['id' => 24, 'raw_type_id' => 3, 'month_id' => 2, 'tonnage_id' => 2, 'price' => 121],
        ['id' => 25, 'raw_type_id' => 3, 'month_id' => 2, 'tonnage_id' => 3, 'price' => 124],
        ['id' => 26, 'raw_type_id' => 3, 'month_id' => 2, 'tonnage_id' => 4, 'price' => 131],
        ['id' => 27, 'raw_type_id' => 3, 'month_id' => 3, 'tonnage_id' => 1, 'price' => 124],
        ['id' => 28, 'raw_type_id' => 3, 'month_id' => 3, 'tonnage_id' => 2, 'price' => 145],
        ['id' => 29, 'raw_type_id' => 3, 'month_id' => 3, 'tonnage_id' => 3, 'price' => 136],
        ['id' => 30, 'raw_type_id' => 3, 'month_id' => 3, 'tonnage_id' => 4, 'price' => 138],
        ['id' => 31, 'raw_type_id' => 3, 'month_id' => 4, 'tonnage_id' => 1, 'price' => 137],
        ['id' => 32, 'raw_type_id' => 3, 'month_id' => 4, 'tonnage_id' => 2, 'price' => 147],
        ['id' => 33, 'raw_type_id' => 3, 'month_id' => 4, 'tonnage_id' => 3, 'price' => 143],
        ['id' => 34, 'raw_type_id' => 3, 'month_id' => 4, 'tonnage_id' => 4, 'price' => 112],
        ['id' => 35, 'raw_type_id' => 3, 'month_id' => 5, 'tonnage_id' => 1, 'price' => 122],
        ['id' => 36, 'raw_type_id' => 3, 'month_id' => 5, 'tonnage_id' => 2, 'price' => 143],
        ['id' => 37, 'raw_type_id' => 3, 'month_id' => 5, 'tonnage_id' => 3, 'price' => 112],
        ['id' => 38, 'raw_type_id' => 3, 'month_id' => 5, 'tonnage_id' => 4, 'price' => 117],
        ['id' => 39, 'raw_type_id' => 3, 'month_id' => 6, 'tonnage_id' => 1, 'price' => 125],
        ['id' => 40, 'raw_type_id' => 3, 'month_id' => 6, 'tonnage_id' => 2, 'price' => 145],
        ['id' => 41, 'raw_type_id' => 3, 'month_id' => 6, 'tonnage_id' => 3, 'price' => 136],
        ['id' => 42, 'raw_type_id' => 3, 'month_id' => 6, 'tonnage_id' => 4, 'price' => 138],

        ['id' => 43, 'raw_type_id' => 1, 'month_id' => 1, 'tonnage_id' => 1, 'price' => 137],
        ['id' => 44, 'raw_type_id' => 1, 'month_id' => 1, 'tonnage_id' => 2, 'price' => 147],
        ['id' => 45, 'raw_type_id' => 1, 'month_id' => 1, 'tonnage_id' => 3, 'price' => 112],
        ['id' => 46, 'raw_type_id' => 1, 'month_id' => 1, 'tonnage_id' => 4, 'price' => 122],
        ['id' => 47, 'raw_type_id' => 1, 'month_id' => 2, 'tonnage_id' => 1, 'price' => 125],
        ['id' => 48, 'raw_type_id' => 1, 'month_id' => 2, 'tonnage_id' => 2, 'price' => 145],
        ['id' => 49, 'raw_type_id' => 1, 'month_id' => 2, 'tonnage_id' => 3, 'price' => 136],
        ['id' => 50, 'raw_type_id' => 1, 'month_id' => 2, 'tonnage_id' => 4, 'price' => 138],
        ['id' => 51, 'raw_type_id' => 1, 'month_id' => 3, 'tonnage_id' => 1, 'price' => 124],
        ['id' => 52, 'raw_type_id' => 1, 'month_id' => 3, 'tonnage_id' => 2, 'price' => 145],
        ['id' => 53, 'raw_type_id' => 1, 'month_id' => 3, 'tonnage_id' => 3, 'price' => 136],
        ['id' => 54, 'raw_type_id' => 1, 'month_id' => 3, 'tonnage_id' => 4, 'price' => 138],
        ['id' => 55, 'raw_type_id' => 1, 'month_id' => 4, 'tonnage_id' => 1, 'price' => 122],
        ['id' => 56, 'raw_type_id' => 1, 'month_id' => 4, 'tonnage_id' => 2, 'price' => 143],
        ['id' => 57, 'raw_type_id' => 1, 'month_id' => 4, 'tonnage_id' => 3, 'price' => 112],
        ['id' => 58, 'raw_type_id' => 1, 'month_id' => 4, 'tonnage_id' => 4, 'price' => 117],
        ['id' => 59, 'raw_type_id' => 1, 'month_id' => 5, 'tonnage_id' => 1, 'price' => 137],
        ['id' => 60, 'raw_type_id' => 1, 'month_id' => 5, 'tonnage_id' => 2, 'price' => 119],
        ['id' => 61, 'raw_type_id' => 1, 'month_id' => 5, 'tonnage_id' => 3, 'price' => 141],
        ['id' => 62, 'raw_type_id' => 1, 'month_id' => 5, 'tonnage_id' => 4, 'price' => 117],
        ['id' => 63, 'raw_type_id' => 1, 'month_id' => 6, 'tonnage_id' => 1, 'price' => 121],
        ['id' => 64, 'raw_type_id' => 1, 'month_id' => 6, 'tonnage_id' => 2, 'price' => 118],
        ['id' => 65, 'raw_type_id' => 1, 'month_id' => 6, 'tonnage_id' => 3, 'price' => 137],
        ['id' => 66, 'raw_type_id' => 1, 'month_id' => 6, 'tonnage_id' => 4, 'price' => 142],
    ];
